language: objective-c  #1
osx_image: xcode8.2 #2
xcode_workspace: UProgress.xcworkspace #3
xcode_scheme: UProgress #4
script:
- xcodebuild clean build test -sdk iphonesimulator -workspace UProgress.xcworkspace -scheme UProgress -destination "platform=iOS Simulator,name=iPhone SE,OS=10.2" CODE_SIGNING_REQUIRED=NO
